# SimFDASEE

## Description

This repository contains the code for the simulation study presented in the article ["Robust Functional Data Analysis for Stochastic Evolution Equations"](https://arxiv.org/abs/2401.16286) by Dennis Schroers.

The simulation study compares the finite-sample performance of the truncated covariation estimator for adjusted increments and nonadjusted increments in the context of a first order stochastic PDE.

---
  
## Main Files

- `Simulation_Study_ad_hoc_trunc.R`: Main R script for replicating the simulation study with ad-hoc chosen levels of truncation.
- `Simulation_Study_rank_based.R`: Main R script for replicating the simulation study with truncation based on a data-driven rule.
- `results/simulation_results_conserv_exponential.csv`: Output of the simulation study using the exponential kernel and ad-hoc truncation.
- `results/simulation_results_exponential.csv`: Output of the simulation study using the exponential kernel and data-driven truncation.
- `results/simulation_results_conserv_gaussian.csv`: Output of the simulation study using the Gaussian kernel and ad-hoc truncation.
- `results/simulation_results_gaussian.csv`: Output of the simulation study using the Gaussian kernel and data-driven truncation.

## Installation
  
To use the package, install the development version with devtools:

  
  ```r
# Install devtools if needed
install.packages("devtools")


# Install the package from GitHub
devtools::install_github("yourusername/SimFDASEE")
```  

## Usage Example

```r
library(SimFDASEE)

# Run a small simulation
res <- run_mc_simulation(
  K = 10, 
  nx = 101, 
  nt = 101, 
  kernel = function(h) exp(-abs(h))
)

# View results
print(res$results)
```



